version: '3.7'

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    image: builder
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
